### ISSUE TITLE
Error on import from server

### ISSUE THREAD

**Issue by vedina** [ideaconsult/i5#1]
i5-1.2.1

```
java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
    at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:133)
    at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:160)
    at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:144)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:423)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at net.idea.i5.cli.SessionClient.post(SessionClient.java:73)
    at net.idea.i5.cli.SessionClient.login(SessionClient.java:47)
    at net.idea.i5.cli.I5LightClient.login(I5LightClient.java:21)
    at ambit2.db.processors.CallableSubstanceI5Query.doCall(CallableSubstanceI5Query.java:303)
```

**Comment by vedina** [comment]
this was fixed in ambit 3.0.3 release
